### ISSUE TITLE
Distorted compiled hat

### ISSUE THREAD

**Issue by JulienSpicowicz** [CloneTrooper1019/Rbx2Source#24]
The captain squid head (part of a package) comes out very distorted if compiled on a character's head and is just invisble when compiled by itself

[No Hat](https://i.imgur.com/o8iLljV.png)
[With Hat](https://i.imgur.com/h6DAkTc.png)
[My character that i used to compile](https://www.roblox.com/users/56089045/profile)

**Comment by CloneTrooper1019** [comment]
Alright, I think I was able to trace down why this was happening.
It turns out I was reading non-orthogonal orientations incorrectly in the binary file format.
I've rolled out a patch that should fix this. Let me know if you're still seeing the problem.
https://github.com/CloneTrooper1019/Rbx2Source/commit/bf699c3c782a0218213b9cb2b151f05f67e25cf0

**Comment by JulienSpicowicz** [comment]
It works now! Thanks for taking the time to fix it
