### ISSUE TITLE
The UGC item loads normally as a standalone accessory but not with players.

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#55]
![image](https://user-images.githubusercontent.com/45589944/94364492-42f45700-00fc-11eb-845b-f442e8b836e6.png)
idk why this happens away
original avatar:
![image](https://user-images.githubusercontent.com/45589944/94364500-4ee01900-00fc-11eb-8431-d4d3f01261cf.png)

**Comment by B1ackydecatty** [comment]
i have checked both items on the face and it loads fine as an accessory
here, screenshots.
![image](https://user-images.githubusercontent.com/45589944/94364521-6d461480-00fc-11eb-9775-7705f3814d2e.png)
(its closed up for some reason)
![image](https://user-images.githubusercontent.com/45589944/94364531-82bb3e80-00fc-11eb-9075-77bfa35b8bf5.png)
Item links:
https://www.roblox.com/catalog/4904654004/Shadowed-Head
https://www.roblox.com/catalog/4794060642/Void-Head

**Comment by B1ackydecatty** [comment]
I don't know where the source of the root problem so i could send you the model if you wanna check why it happens.

**Comment by nonobou31** [comment]
As you may not know roblox uses a big texture for every model like the player (exemple under big texture / player ). Sometimes due to limitation roblox does 2 ( or more ) texture for avatars that have too much hats (normaly with the 3 hat limit it would be possible but now with ugc and waist and all that suff like accesories the limit is way past what roblox intended in 200X) . So i think roblox 2 source dosn't think abbout those other texture due to the two texture (or more ) that not a lot ppl could reatch when rblx2sorce wasn't realeased yet .


sorry for the bad ortograph im french
![Nonowastaken1Tex](https://user-images.githubusercontent.com/28670447/101943735-ed542480-3beb-11eb-867f-74034000e620.png)
![Png](https://user-images.githubusercontent.com/28670447/101943857-22607700-3bec-11eb-8b8c-296ef8e5fa52.png)

**Comment by CloneTrooper1019** [comment]
That shouldn’t be the problem @nonobou31. I keep accessory textures split from the body texture map so they’ll all load regardless of how many accessories are thrown at it. Plus the texture composition you’re showing there is for R6, not R15.

Does this problem still happen for you as of the latest patch @B1ackydecatty?

**Comment by B1ackydecatty** [comment]
gonna check again

**Comment by B1ackydecatty** [comment]
doesn't happen anymore thanks alot
