### ISSUE TITLE
Model Leaks

### ISSUE THREAD

**Issue by JulienSpicowicz** [CloneTrooper1019/Rbx2Source#9]
Whenever i try to compile a character/item it always leaks

	qdir:    "c:\users\pessoal\appdata\roaming\rbx2source\avatars\TELER1K\model\"
	gamedir: "D:\SteamLibrary\steamapps\common\GarrysMod\garrysmod\"
	g_path:  "C:\Users\Pessoal\AppData\Roaming\Rbx2Source\Avatars\TELER1K\Model\Compile.qc"
	Building binary model files...
	Working on "Compile.qc"
	SMD MODEL CharacterModel.smd
	ERROR: MdlError(33) : 0 0,000000 0,000000 0,000000 0,000000 0,000000 0,000000
	WARNING: Leaking 1 elements

**Comment by CloneTrooper1019** [comment]
Is this still happening?

**Comment by JulienSpicowicz** [comment]
Still happening

**Comment by CloneTrooper1019** [comment]
Alright, I figured out why this is happening.

.NET has this really annoying `number -> string` converter where it will represent the strings based on the language you have set on Windows. The `0,000000` values should be `0.000000`, hence why the issue is occurring.

I'll have a patch out for this shortly.

**Comment by CloneTrooper1019** [comment]
Let me know if you guys are still seeing this after the patch I just rolled out.

**Comment by JulienSpicowicz** [comment]
Yup seems to be working! Thank you!

**Comment by CloneTrooper1019** [comment]
Can you file a separate issue with instructions to reproduce it? I'll see what I can do about it.
